name: Test cURL
on: 
  workflow_dispatch:
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Pull flask image
      run: docker pull digitalocean/flask-helloworld
      
    - name: Run image
      run: docker run -d -p 5000:5000 digitalocean/flask-helloworld

    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.2

#     - name: Print Public IP
#       run: |
#         echo ${{ steps.ip.outputs.ipv4 }}
#         echo ${{ steps.ip.outputs.ipv6 }}

#     - name : check ports
#       run: sudo netstat -tunlp
      
    - name: GET req
      run: |
        curl http://0.0.0.0:5000 
   
