name: Test cURL
on: 
  push:
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: Run python
      run: pip install flask
    
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.2

    - name: Print Public IP
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}
        echo ${{ steps.ip.outputs.ipv6 }}
    
    - name: Run script
      run: cd .github/workflows
          | pwd
          
   
