name: Test cURL
on: 
  push:
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: Run python
      run: pip install flask
    - name: Run script
      run: pwd
          
    - name: curl
      uses: wei/curl@master
      with:
        args: http://127.0.0.1:5000
