name: Test cURL
on: 
  push:
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: Run python
      run: pip install flask
          | python script.py
          
    - name: curl
      uses: wei/curl@master
      with:
        args: http://0.0.0.0/5001
