name: Linting Docs on push

on:
  push: 
  
jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Vale
      uses: errata-ai/vale-action@reviewdog
      with:
          reporter: github-check # checks errors in all rst files on commit
          fail_on_error: true

      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
