name: Linting Docs on PR

on:
  pull_request: 
  
jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Vale
      uses: errata-ai/vale-action@reviewdog
      with:
          reporter: github-pr-check # Errors in the files through the PR are checked and reported
          fail_on_error: true

      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
